# Generated by Django 4.1.7 on 2023-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5app', '0009_alter_attendance_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images/')),
                ('checkin_time', models.DateTimeField()),
            ],
        ),
    ]
